language: node_js
node_js:
  - 16
before_install:
  - npm install -g npm@latest
install:
  - npm ci
jobs:
  include:
    - stage: validate
      script: npm run validate-yaml
cache:
  directories:
    - "$HOME/.npm"
    - ".cache" 
